USE EstanteVirtual
GO

INSERT INTO [dbo].[Login] VALUES('joao@gmail.com', 123)
INSERT INTO [dbo].[User] VALUES('João', 1)

INSERT INTO [dbo].[Login] VALUES('ricardo@gmail.com', 123)
INSERT INTO [dbo].[User] VALUES('Ricardo', 2)

INSERT INTO Author VALUES ('Gabriel Garcia Marquez')
INSERT INTO Author VALUES ('Neil Gaiman')
INSERT INTO Author VALUES ('Philip K. Dick')

INSERT INTO Book VALUES('Cem anos de solidão', 'assets/img/cem_anos_de_solidao.jpg', 'O livro mais importante de Gabriel Garcia Márquez. Neste que é um dos maiores clássicos da literatura, o prestigiado autor narra a incrível e triste história dos Buendía – a estirpe de solitários para a qual não será dada “uma segunda oportunidade sobre a terra” e apresenta o maravilhoso universo da fictícia Macondo, onde se passa o romance. É lá que acompanhamos diversas gerações dessa família, assim como a ascensão e a queda do vilarejo. Para além dos artifícios técnicos e das influências literárias que transbordam do livro, ainda vemos em suas páginas o que por muitos é considerado uma autêntica enciclopédia do imaginário, num estilo que consagrou o colombiano como um dos maiores autores do século XX.', 1)
INSERT INTO Book VALUES('Do amor e outros demônios', 'assets/img/do_amor_e_outros_demonios.jpg', 'Um livro sobre o desejo que elege as paixões e atinge as raízes mais profundas do ser humano: o amor. Em 1949, o convento histórico de Santa Clara seria vendido para a construção de um hotel cinco estrelas no local. E Gabriel García Márquez, um jovem repórter, é designado para acompanhar a remoção das criptas funerárias da capela. O que mais impressinou este colombiano foi o túmulo de uma menina, que o fez lembrar as lendas contadas por sua avó. Segundo ela, no Caribe, havia uma marquesinha que tinha uma “cabeleira que se arrastava como a cauda de um vestido de noiva”. Venerada por seus milagres, ela foi mordida por um cachorro e morreu de raiva. Seria aquela marquesinha de sua infância ali enterrada? García Márquez conta a história da filha única de um marquês, criada no convívio de escravos e orixás, e um padre incumbido de exorcizar os demônios que se acredita terem possuído a pequena, cujos cabelos só seriam cortados em seu casamento.', 1)
INSERT INTO Book VALUES('Ninguém escreve ao coronel', 'assets/img/ninguem_escreve_ao_coronel.jpg', 'Enquanto espera o pagamento de sua aposentadoria pelo correio, um coronel reformado luta para sobreviver em uma cidadezinha hostil. Ao seu lado, apenas a mulher asmática e um galo de briga que pertencia a seu falecido filho. A correspondência sempre chega uma vez por semana, às sextas-feiras, mas a aposentadoria não, perdida nos trâmites burocráticos. “Ninguém escreve ao coronel”, diz com desdém o carteiro. Uma trama simples, mas repleta de ironia e comentários sutis sobre a história e a política de seu país.', 1)
INSERT INTO Book VALUES('American Gods', 'assets/img/american_gods.jpg', 'Deuses americanos é, acima de tudo, um livro estranho. E foi essa estranheza que tornou o romance de Neil Gaiman, publicado pela primeira vez em 2001, um clássico imediato. Nesta nova edição, preferida do autor, o leitor encontrará capítulos revistos e ampliados, artigos, uma entrevista com Gaiman e um inspirado texto de introdução. Juntos, os livros de Neil Gaiman lançados pela Intrínseca já venderam mais de 100 mil exemplares.', 2)
INSERT INTO Book VALUES('Androides sonham com ovelhas elétricas?', 'assets/img/androis_sonham_com_ovelhas.jpg', 'O LIVRO QUE ORIGINOU O FILME BLADE RUNNER. Philip K. Dick teve diversos livros adaptados para o cinema, mas nenhum foi tão aclamado e tão simbólico para sua época quanto Blade Runner: O Caçador de Androides, de Ridley Scott, que foi inspirado em Androides Sonham com Ovelhas Elétricas?. Em Androides Sonham com Ovelhas Elétricas?, Philip K. Dick cria uma atmosfera sombria e perturbadora para contar uma história impressionante, e, claro, abordar questões filosóficas profundas sobre a natureza da vida, da religião, da tecnologia e da própria condição humana.', 3)